# Much taken from SageMath.
name: kpkc with cysignals on cygwin

on:
  pull_request:
    types: [opened, synchronize]
  push:
    tags:
      - '*'

env:
  MAKE: make -j8
  CYGWIN: winsymlinks:native

jobs:
    build:
        runs-on: windows-latest

        strategy:
          fail-fast: false
          matrix:
            python-version-start: [python-3]
            python-version: [6, 7, 8]
        steps:
        - run: |
            git config --global core.autocrlf false
            git config --global core.symlinks true
        - name: Set up the repository
          uses: actions/checkout@v2
          with:
              submodules: recursive
              fetch-depth: 0
        - name: install cygwin and minimal prerequisites with choco
          shell: bash {0}
          run: |
            choco --version
            choco install make autoconf gcc-core gcc-g++ python3${{ matrix.python-version }}-devel --source cygwin
        - name: install dependencies
          run: |
            C:\\tools\\cygwin\\bin\\bash -l -x -c 'export PATH=/usr/local/bin:/usr/bin && cd $(cygpath -u "$GITHUB_WORKSPACE") && python3.${{ matrix.python-version }} -m pip install setuptools cysignals Cython memory-allocator Sphinx flake8 networkx'
        - name: install
          run: |
            C:\\tools\\cygwin\\bin\\bash -l -x -c 'export PATH=/usr/local/bin:/usr/bin && cd $(cygpath -u "$GITHUB_WORKSPACE") && python3.${{ matrix.python-version }} setup.py build_ext -i'
        - name: test
          run: |
            C:\\tools\\cygwin\\bin\\bash -l -x -c 'export PATH=/usr/local/bin:/usr/bin && cd $(cygpath -u "$GITHUB_WORKSPACE") && python3.${{ matrix.python-version }} test.py'

