name: kpkc-flake8

on:
    pull_request:
        types: [opened, synchronize]
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: [ubuntu-latest]
        steps:
        - name: Set up the repository
          uses: actions/checkout@v2
          with:
              submodules: recursive
              fetch-depth: 0
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
              python-version: 3.8
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install setuptools Cython memory-allocator Sphinx flake8 cysignals
        - name: Lint with flake8
          run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # The GitHub editor is 127 chars wide
            flake8 . --count --max-complexity=10 --max-line-length=127 --statistics --per-file-ignores="kpkc/__init__.py:F401"
